"""Ray-traced S4 (Sionna RT, Munich scene): BLER and CRC-gated adaptation.

The 200 ray-traced channels (results/s4_channels.npy, static per realisation,
unit average power, generated by s4_gen.py) are split once into an adaptation set
(even indices) and a disjoint evaluation set (odd indices).

  1. BLER vs SNR on the evaluation set for AINR, DiscNRX (per training seed) and the
     classical receivers (once), 5 passes over the 100 channels (500 blocks/point).
  2. Adaptation: starting from each trained receiver, CRC-gated one-step updates on a
     stream of slots drawn from the adaptation set (receiver-side CRC16 only), then BLER
     on the evaluation set at the same SNR. Answers whether adaptation removes the
     high-SNR error floor on unseen geometry.

Output: results/ojcoms/s4_bler_seed{s}.csv, s4_bler_classical.csv, s4_adapt_seed{s}.csv
Usage : python exp_s4.py --seeds 0 [--quick]
"""
import argparse
import os

import numpy as np
import torch

from exp_common import (ROOT, DEV, load_cfg, make_channel, load_neural, load_classical,
                        atomic_write_csv)
from src.ainr import AINR
from src.baselines.discriminative_nrx import DiscriminativeNRX
from src.evaluation.metrics import hard_bits

ap = argparse.ArgumentParser()
ap.add_argument("--seeds", type=int, nargs="+", default=[0])
ap.add_argument("--snrs", type=float, nargs="+", default=[0, 5, 10, 15, 20, 25])
ap.add_argument("--passes", type=int, default=5)
ap.add_argument("--adapt_snrs", type=float, nargs="+", default=[5.0, 15.0])
ap.add_argument("--adapt_slots", type=int, default=600)
ap.add_argument("--lr", type=float, default=1e-4)
ap.add_argument("--quick", action="store_true")
args = ap.parse_args()
if args.quick:
    args.passes, args.snrs, args.adapt_slots, args.adapt_snrs = 1, [5, 25], 8, [15.0]

B = 25
cfg = load_cfg(16)
out = os.path.join(ROOT, "results", "ojcoms")
sfx = "_quick" if args.quick else ""
ch = make_channel(cfg)
Hs = torch.tensor(np.load(os.path.join(ROOT, "results", "s4_channels.npy")), dtype=torch.complex64, device=DEV)
ADAPT_IDX = list(range(0, Hs.shape[0], 2))
EVAL_IDX = list(range(1, Hs.shape[0], 2))
N_sym, N_sc, N_rx = ch.n_symbols, ch.n_subcarriers, ch.n_rx


def hfreq(idx):
    H = Hs[idx]                                                   # (B, N_rx, N_sc)
    return H[:, None, :, None, None, None, :].expand(len(idx), 1, N_rx, 1, 1, N_sym, N_sc).contiguous()


def slot_batch(idx, snr):
    """Transmit CRC-protected blocks through RT channels idx at the given SNR."""
    no = float(ch.snr_db_to_no(torch.tensor(float(snr))).item())
    bits = ch.binary_source([len(idx), 1, ch.n_tx, ch.k]).reshape(len(idx), ch.num_info_bits)
    y = ch.apply_channel(ch.transmit(bits), hfreq(idx), torch.full((1, 1, 1, 1, 1), no, device=DEV))
    return ch._received_to_claude_layout(y), bits, no


@torch.no_grad()
def hard(rx, Y, no, idx):
    if isinstance(rx, AINR):
        return hard_bits(rx(Y, record_fe=False))
    if isinstance(rx, DiscriminativeNRX):
        return hard_bits(rx(Y))
    return hard_bits(rx(Y, no=no, h_freq=hfreq(idx)))


def bler_eval(receivers, snr, stream):
    torch.manual_seed(stream)
    err = {k: 0 for k in receivers}; tot = 0
    for _ in range(args.passes):
        for s in range(0, len(EVAL_IDX), B):
            idx = EVAL_IDX[s:s + B]
            Y, bits, no = slot_batch(idx, snr)
            for k, rx in receivers.items():
                err[k] += int((hard(rx, Y, no, idx) != bits).any(1).sum())
            tot += len(idx)
    return err, tot


def bler_rows(receivers, seed):
    rows = []
    for i, snr in enumerate(args.snrs):
        err, tot = bler_eval(receivers, snr, 80_000 + 100 * i)
        for k in receivers:
            rows.append({"seed": seed, "receiver": k, "snr_db": snr, "block_errors": err[k], "n_blocks": tot,
                         "bler": err[k] / tot})
        print(f"[S4 {seed}] SNR={snr:4.0f} " + " ".join(f"{k}={err[k] / tot:.3f}" for k in receivers), flush=True)
    return rows


cpath = os.path.join(out, f"s4_bler_classical{sfx}.csv")
if args.quick or not os.path.exists(cpath):
    atomic_write_csv(cpath, bler_rows(load_classical(cfg, ch), -1))

for seed in args.seeds:
    p = os.path.join(out, f"s4_bler_seed{seed}{sfx}.csv")
    if args.quick or not os.path.exists(p):
        ainr, disc = load_neural(cfg, ch, seed)
        atomic_write_csv(p, bler_rows({"AINR": ainr, "DiscNRX": disc}, seed))
        del ainr, disc
    pa = os.path.join(out, f"s4_adapt_seed{seed}{sfx}.csv")
    if not args.quick and os.path.exists(pa):
        continue
    arows = []
    for snr in args.adapt_snrs:
        for rx_name in ("AINR", "DiscNRX"):
            ainr, disc = load_neural(cfg, ch, seed)
            rx = ainr if rx_name == "AINR" else disc
            before, tot = bler_eval({rx_name: rx}, snr, 81_000 + int(snr))
            g = torch.Generator().manual_seed(90_000 + seed)
            order = [ADAPT_IDX[int(j)] for j in torch.randint(len(ADAPT_IDX), (args.adapt_slots,), generator=g)]
            torch.manual_seed(82_000 + int(snr))
            n_upd = n_fp = 0
            for t in range(args.adapt_slots):
                idx = [order[t]]
                Y, bits, no = slot_batch(idx, snr)
                hb = hard(rx, Y, no, idx)
                if bool(ch.crc_check(hb)[0]):                       # receiver-side CRC only
                    rx.adapt_online(Y, hb, lr=args.lr); rx.eval()
                    n_upd += 1; n_fp += int(bool((hb != bits).any()))
            after, _ = bler_eval({rx_name: rx}, snr, 81_000 + int(snr))  # same eval stream as 'before'
            arows.append({"seed": seed, "receiver": rx_name, "snr_db": snr, "bler_before": before[rx_name] / tot,
                          "bler_after": after[rx_name] / tot, "n_blocks": tot, "adapt_slots": args.adapt_slots,
                          "updates": n_upd, "false_pass_updates": n_fp})
            print(f"[S4 adapt {seed}] {rx_name:7s} {snr:4.0f} dB: {before[rx_name] / tot:.3f} -> "
                  f"{after[rx_name] / tot:.3f} ({n_upd} updates, {n_fp} false-pass)", flush=True)
            del ainr, disc, rx
            torch.cuda.empty_cache()
    atomic_write_csv(pa, arows)
print("S4_DONE", flush=True)
