"""Generate the LaTeX results tables of the manuscript from FINAL_OJCOMS/data/*.csv.

Every number in a table comes from the analysis outputs; tables whose experiments
have not finished are emitted with a visible \\pending marker instead of numbers.

Usage: python make_tables.py        (run after analyze_results.py)
"""
import csv
import math
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "FINAL_OJCOMS", "data")
RES = os.path.join(ROOT, "results", "ojcoms")
OUT = os.path.join(ROOT, "FINAL_OJCOMS", "tables")
os.makedirs(OUT, exist_ok=True)


def read(p):
    if not os.path.exists(p):
        return []
    with open(p, newline="") as f:
        return list(csv.DictReader(f))


def seeds_word(n):
    """'Seed' or 'Seeds' for a caption, from the actual seed count (n may be a string)."""
    try:
        return "Seed" if int(float(n)) == 1 else "Seeds"
    except (TypeError, ValueError):
        return "Seeds"


def f3(x):
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "--"
    return "--" if v != v else f"{v:.3f}"


def write(name, text):
    with open(os.path.join(OUT, name) + ".tmp", "w", encoding="utf-8") as f:
        f.write("% Auto-generated by make_tables.py from FINAL_OJCOMS/data -- do not edit by hand.\n" + text)
    os.replace(os.path.join(OUT, name) + ".tmp", os.path.join(OUT, name))
    print(f"  -> FINAL_OJCOMS/tables/{name}")


# ------------------------------------------------------------------ Table: drift detection
def tab_detection():
    A = read(os.path.join(DATA, "detector_auc_summary.csv"))
    R = read(os.path.join(DATA, "detector_relevance.csv"))
    if not A:
        return
    conds = [("DS600", "DS\\,600"), ("DS1000", "DS\\,1000"), ("S2", "S2"), ("CDLD", "CDL-D"),
             ("V90", "90\\,km/h"), ("V250", "250\\,km/h"), ("V400", "400\\,km/h")]
    stats = [("resid", "Residual $\\mathcal{E}$"), ("tdisp", "Temporal disp.\\ $\\mathcal{D}$"),
             ("comb", "Combined"), ("conf_a", "Confidence, AINR"), ("conf_d", "Confidence, DiscNRX"),
             ("crcfail_d", "CRC failure, DiscNRX"), ("cf", "Pilot freq.\\ corr.\\ $|z|$"),
             ("ymag", "Mean $|Y|$ $|z|$")]
    get = {(r["snr_db"], r["window"], r["stat"], r["cond"]): r for r in A}
    rho = defaultdict(list)
    for r in R:
        if r["snr_db"] == "5.0" and r["spearman_rho"] not in ("", "nan"):
            rho[r["stat"]].append(float(r["spearman_rho"]))
    n = A[0]["n_seeds"]
    lines = []
    for s, lab in stats:
        cells = []
        for c, _ in conds:
            r = get.get(("5.0", "1", s, c))
            cells.append(f3(r["auc_mean"]) if r else "--")
        rr = rho.get(s, [])
        cells.append(f"{sum(rr) / len(rr):.2f}" if rr else "--")
        lines.append(f"{lab} & " + " & ".join(cells) + " \\\\")
    head = " & ".join(l for _, l in conds)
    write("tab_detection.tex", f"""\\begin{{table*}}[t]
\\caption{{Single-Slot Detection AUC Against the Matched Condition at 5~dB and Rank Correlation
With the BLER Increase ({n} Training {seeds_word(n)}, {{\\nBlocksCond}} Test Slots per Condition)}}
\\label{{tab:detection}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}l{'c' * len(conds)}c@{{}}}}
\\toprule
& \\multicolumn{{{len(conds)}}}{{c}}{{AUC (single slot)}} & Spearman \\\\
\\cmidrule(lr){{2-{len(conds) + 1}}}
Statistic & {head} & $\\rho$ \\\\
\\midrule
{chr(10).join(lines)}
\\bottomrule
\\end{{tabular}}
\\end{{table*}}
""")


# ------------------------------------------------------------------ Table: ablation
def tab_ablation():
    rows = read(os.path.join(DATA, "ablation_all.csv"))
    if not rows:
        return
    variants = [("full", "Full (reference)", "--"),
                ("no_pilot", "No pilot reference", "Is the LS input needed?"),
                ("pure_vfe", "Pure VFE (no BCE)", "Can the likelihood alone train detection?"),
                ("no_detach", "No stop-gradient", "Should the VFE shape the backbone?"),
                ("no_freeze", "No noise freeze", "Is the warm-up needed?")]
    bler = defaultdict(list); shift = defaultdict(list); seeds = defaultdict(set)
    for r in rows:
        if r["kind"] == "bler":
            bler[(r["variant"], float(r["snr_db"]))].append(float(r["bler"]))
        elif r["kind"] == "shift":
            shift[(r["variant"], r["cond"])].append(float(r["bler"]))
        seeds[r["variant"]].add(r["seed"])

    def m(v):
        return f"{sum(v) / len(v):.3f}" if v else "--"
    lines = []
    for v, lab, q in variants:
        if not seeds.get(v):
            continue
        cells = [m(bler[(v, 1.0)]), m(bler[(v, 3.0)]), m(shift[(v, "S1")]), m(shift[(v, "DS1000")]),
                 m(shift[(v, "S2")]), m(shift[(v, "V250")]), str(len(seeds[v]))]
        lines.append(f"{lab} & " + " & ".join(cells) + " \\\\")
    write("tab_ablation.tex", """\\begin{table*}[t]
\\caption{Ablation of the Training Design (Retrained From Scratch for $1.2\\times10^{4}$ Steps;
1280 Blocks per Entry; Mean Over Seeds)}
\\label{tab:ablation}
\\centering
\\footnotesize
\\setlength{\\tabcolsep}{4pt}
\\begin{tabular}{@{}lccccccc@{}}
\\toprule
& \\multicolumn{2}{c}{Matched BLER} & \\multicolumn{4}{c}{BLER at 5~dB under shift} & \\\\
\\cmidrule(lr){2-3}\\cmidrule(lr){4-7}
Variant & 1~dB & 3~dB & S1 & DS\\,1000 & S2 & 250\\,km/h & Seeds \\\\
\\midrule
""" + "\n".join(lines) + """
\\bottomrule
\\end{tabular}
\\end{table*}
""")


# ------------------------------------------------------------------ Table: adaptation
def tab_adapt():
    rows = read(os.path.join(DATA, "adapt_summary.csv"))
    if not rows:
        return
    order = ["none", "ungated", "gated", "trig"]
    lab = {"none": "None", "ungated": "Ungated", "gated": "CRC-gated", "trig": "Triggered + CRC"}
    by = {(r["snr_db"], r["receiver"], r["mode"]): r for r in rows}
    lines = []
    for snr in ("3.0", "5.0"):
        for rx in ("AINR", "DiscNRX"):
            for i, md in enumerate(order):
                r = by.get((snr, rx, md))
                if not r:
                    continue
                pre = (f"\\multirow{{4}}{{*}}{{{float(snr):g}~dB}} & \\multirow{{4}}{{*}}{{{rx}}}" if (rx == "AINR" and i == 0)
                       else (f" & \\multirow{{4}}{{*}}{{{rx}}}" if i == 0 else " & "))
                if rx == "DiscNRX" and i == 0:
                    pre = f" & \\multirow{{4}}{{*}}{{{rx}}}"
                # One recovery slot per seed. Listing them all made the column grow with the
                # seed count (and overflow the text block), so report how many runs recovered
                # and the median slot among them; the per-seed slots stay in data/adapt_summary*.csv.
                import statistics as _st
                rec = r["recovery_slots"].split()
                done = [float(x) for x in rec if x != "inf"]
                if not done:
                    recs = "never"
                elif len(done) == len(rec):
                    recs = f"all ({_st.median(done):.0f})"
                else:
                    recs = f"{len(done)}/{len(rec)} ({_st.median(done):.0f})"
                ms = "--" if r["median_update_ms"] in ("", "nan") else f"{float(r['median_update_ms']):.0f}"
                lines.append(f"{pre} & {lab[md]} & {f3(r['first200'])} & {f3(r['last200'])} & "
                             f"{float(r['accepted_updates']):.0f} & {float(r['false_pass_updates']):.0f} & {recs} & {ms} \\\\")
            lines.append("\\cmidrule(l){2-9}" if rx == "AINR" else "\\midrule")
    lines[-1] = ""
    n = rows[0]["n_seeds"]
    write("tab_adapt.tex", f"""\\begin{{table*}}[t]
\\caption{{Online Adaptation After the S2 Shift With a Receiver-Side CRC16 (1000 Slots per Run;
Mean Over {n} Training {seeds_word(n)}, Including Runs Whose CRC Pass Rate Was Zero and Which
Therefore Never Adapt; Recovery Column: Runs That Recovered Out of All Runs, With the Median
Recovery Slot in Parentheses; Update Latency Measured During the Run)}}
\\label{{tab:adapt}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}lllcccccc@{{}}}}
\\toprule
SNR & Receiver & Mode & BLER, slots 1--200 & BLER, slots 801--1000 & Updates & False-pass updates & Recovery slot & Update (ms) \\\\
\\midrule
{chr(10).join(l for l in lines if l)}
\\bottomrule
\\end{{tabular}}
\\end{{table*}}
""")


def tab_matched():
    cr = read(os.path.join(DATA, "matched_snr01.csv"))
    if not cr:
        return False
    import statistics
    lines = []
    for qam in ("16", "64"):
        rxs = [r for r in ("AINR", "DiscNRX", "LS-LIN", "LS-LMMSE", "PCSI") if any(c["qam"] == qam and c["receiver"] == r for c in cr)]
        for i, rx in enumerate(rxs):
            v = [float(c["snr_at_bler_0p1"]) for c in cr if c["qam"] == qam and c["receiver"] == rx]
            v = [x for x in v if x == x]
            n = len([c for c in cr if c["qam"] == qam and c["receiver"] == rx])
            if not v:
                cell = "not reached"
            elif len(v) > 1:
                import math as _m
                from scipy import stats as _st
                h = _st.t.ppf(0.975, len(v) - 1) * statistics.stdev(v) / _m.sqrt(len(v))
                cell = f"{statistics.mean(v):.2f} $\\pm$ {h:.2f}"
            else:
                cell = f"{v[0]:.2f}"
            seeds = "--" if rx.startswith(("LS", "PC")) else str(n)
            q = f"\\multirow{{{len(rxs)}}}{{*}}{{{qam}-QAM}}" if i == 0 else ""
            lines.append(f"{q} & {rx} & {cell} & {seeds} \\\\")
        lines.append("\\midrule")
    lines = lines[:-1]
    write("tab_matched.tex", """\\begin{table}[t]
\\caption{SNR (dB) at BLER $=0.1$ on the Matched Channel (Mean $\\pm$ 95\\% Interval Over Training Seeds)}
\\label{tab:matched}
\\centering
\\footnotesize
\\begin{tabular}{@{}llcc@{}}
\\toprule
Modulation & Receiver & SNR at BLER $=0.1$ & Seeds \\\\
\\midrule
""" + "\n".join(lines) + """
\\bottomrule
\\end{tabular}
\\end{table}
""")
    return True


def tab_s4():
    s = read(os.path.join(DATA, "s4_summary.csv"))
    a = read(os.path.join(DATA, "s4_adapt_summary.csv"))
    if not s:
        return False
    get = {(r["receiver"], float(r["snr_db"])): r for r in s}
    snrs = [5.0, 15.0, 25.0]
    lines = []
    for rx in ("AINR", "DiscNRX", "LS-LIN", "LS-LMMSE", "PCSI"):
        cells = [f3(get[(rx, x)]["bler_mean"]) if (rx, x) in get else "--" for x in snrs]
        ad = {float(r["snr_db"]): r for r in a if r["receiver"] == rx}
        adc = [f"{f3(ad[x]['bler_before'])} $\\rightarrow$ {f3(ad[x]['bler_after'])}" if x in ad else "--" for x in (5.0, 15.0)]
        lines.append(f"{rx} & " + " & ".join(cells + adc) + " \\\\")
    write("tab_s4.tex", """\\begin{table*}[t]
\\caption{BLER on the Ray-Traced Scene S4 (Evaluation Half) and Before $\\rightarrow$ After CRC-Gated Adaptation on the Disjoint Adaptation Half}
\\label{tab:s4}
\\centering
\\footnotesize
\\begin{tabular}{@{}lccccc@{}}
\\toprule
& \\multicolumn{3}{c}{BLER} & \\multicolumn{2}{c}{Adaptation (600 slots)} \\\\
\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}
Receiver & 5~dB & 15~dB & 25~dB & 5~dB & 15~dB \\\\
\\midrule
""" + "\n".join(lines) + """
\\bottomrule
\\end{tabular}
\\end{table*}
""")
    return True


def tab_complexity():
    c = read(os.path.join(RES, "complexity.csv"))
    if not c:
        return False
    def med(stage, rx, b):
        for r in c:
            if r["stage"] == stage and r["receiver"] == rx and r.get("batch") in (str(b), f"{b}.0"):
                return float(r["median_ms"])
        return float("nan")
    st = {r["receiver"]: r for r in c if r["stage"] == "static"}
    rows = [("AINR detection", med("detection", "AINR", 1), med("detection", "AINR", 32), st.get("AINR", {}).get("params", ""), st.get("AINR", {}).get("macs_per_slot", "")),
            ("DiscNRX detection", med("detection", "DiscNRX", 1), med("detection", "DiscNRX", 32), st.get("DiscNRX", {}).get("params", ""), st.get("DiscNRX", {}).get("macs_per_slot", "")),
            ("LS-LIN detection", med("detection", "LS-LIN", 1), med("detection", "LS-LIN", 32), "--", "--"),
            ("LS-LMMSE detection", med("detection", "LS-LMMSE", 1), med("detection", "LS-LMMSE", 32), "--", "--"),
            ("of which CNN (AINR)", med("cnn", "AINR", 1), med("cnn", "AINR", 32), "", ""),
            ("of which LDPC BP", med("ldpc", "shared", 1), med("ldpc", "shared", 32), "", ""),
            ("Monitor, $S=1$", med("monitor", "AINR S=1", 1), med("monitor", "AINR S=1", 32), "", ""),
            ("Monitor, $S=4$", med("monitor", "AINR S=4", 1), med("monitor", "AINR S=4", 32), "", ""),
            ("CRC16 check", med("crc", "shared", 1), med("crc", "shared", 32), "", ""),
            ("Adaptation step, AINR", med("adapt", "AINR", 1), float("nan"), "", ""),
            ("Adaptation step, DiscNRX", med("adapt", "DiscNRX", 1), float("nan"), "", "")]
    def ms(x):
        return "--" if x != x else f"{x:.1f}"
    def big(x):
        try:
            v = float(x)
            e = int(math.floor(math.log10(v)))
            return f"${v / 10 ** e:.2f}\\times10^{{{e}}}$"
        except (TypeError, ValueError):
            return x
    lines = [f"{a} & {ms(b)} & {ms(c_)} & {big(d)} & {big(e)} \\\\" for a, b, c_, d, e in rows]
    write("tab_complexity.tex", """\\begin{table}[t]
\\caption{Complexity and Latency (Median of 50 CUDA-Synchronized Calls, GPU Otherwise Idle)}
\\label{tab:complexity}
\\centering
\\footnotesize
\\setlength{\\tabcolsep}{2pt}
\\begin{tabular}{@{}lcccc@{}}
\\toprule
Stage & $B{=}1$ & $B{=}32$ & Params & MACs \\\\
 & (ms) & (ms) & & (per slot) \\\\
\\midrule
""" + "\n".join(lines) + """
\\bottomrule
\\end{tabular}
\\end{table}
""")
    return True


def supp_tables():
    """Supplementary tables (supplementary/supplementary.tex)."""
    inv = read(os.path.join(DATA, "inversion_summary.csv"))
    if inv:
        lines = []
        for r in inv:
            lines.append(f"{r['config'].replace('QAM-K', '-QAM, $K=')}$ & {r['init']} & {f3(r['final_coded_ber_mean'])} & "
                         f"{f3(r['post_bp_bler_mean'])} & {f3(r['final_info_ber_mean'])} & {float(r['final_grad_info_mean']):.3g} & "
                         f"{float(r['final_grad_coded_mean']):.3g} & {r['n_seeds']} \\\\")
        write("tab_supp_inversion.tex", """\\begin{table}[h]
\\caption{Controlled inversion for all codes and initializations (mean over seeds; 1500 Adam steps, 10~dB, perfect CSI)}
\\label{tab:supp-inversion}
\\centering\\footnotesize
\\begin{tabular}{@{}llcccccc@{}}
\\toprule
Code & Init. & Coded BER & BLER after BP & Info.\\ BER & $|\\nabla|$ info. & $|\\nabla|$ coded & Seeds \\\\
\\midrule
""" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    T = read(os.path.join(DATA, "detector_tpr_summary.csv"))
    if T:
        conds = ["DS600", "DS1000", "S2", "V150", "V250", "V400"]
        stats = [("resid", "Residual"), ("tdisp", "Temporal disp."), ("comb", "Combined"), ("conf_a", "Conf.\\ AINR"),
                 ("conf_d", "Conf.\\ DiscNRX"), ("crcfail_d", "CRC fail DiscNRX")]
        get = {(r["snr_db"], r["window"], r["stat"], r["cond"], r["alpha"]): r for r in T}
        blocks = []
        for W in ("1", "8"):
            lines = []
            for s, lab in stats:
                cells = []
                for c in conds:
                    r = get.get(("5.0", W, s, c, "0.05"))
                    cells.append(f3(r["tpr_mean"]) if r else "--")
                fpr = get.get(("5.0", W, s, "S2", "0.05"))
                lines.append(f"{lab} & " + " & ".join(cells) + f" & {f3(fpr['realised_fpr_mean']) if fpr else '--'} \\\\")
            blocks.append(f"\\multicolumn{{8}}{{@{{}}l}}{{\\emph{{Window $W={W}$ slot(s)}}}} \\\\\n" + "\n".join(lines))
        write("tab_supp_tpr.tex", """\\begin{table}[h]
\\caption{True-positive rate at a 5\\% false-alarm target (threshold from the matched validation stream) at 5~dB, and the realized false-alarm rate on the matched test stream}
\\label{tab:supp-tpr}
\\centering\\footnotesize
\\begin{tabular}{@{}lccccccc@{}}
\\toprule
Statistic & DS\\,600 & DS\\,1000 & S2 & 150\\,km/h & 250\\,km/h & 400\\,km/h & Realized FPR \\\\
\\midrule
""" + "\n\\midrule\n".join(blocks) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    A = read(os.path.join(DATA, "detector_auc_summary.csv"))
    if A:
        conds = [("DS200", "DS\\,200"), ("DS600", "DS\\,600"), ("DS1000", "DS\\,1000"), ("S2", "S2"), ("CDLD", "CDL-D"),
                 ("V90", "90\\,km/h"), ("V250", "250\\,km/h")]
        stats = [("resid", "Residual"), ("tdisp", "Temporal disp."), ("comb", "Combined"), ("conf_a", "Conf.\\ AINR"),
                 ("conf_d", "Conf.\\ DiscNRX"), ("cf", "Pilot freq.\\ corr.")]
        get = {(r["snr_db"], r["window"], r["stat"], r["cond"]): r for r in A}
        for snr, W, name, cap in (("10.0", "1", "tab_supp_auc10.tex", "Single-slot AUC at 10~dB"),
                                  ("5.0", "8", "tab_supp_aucwin.tex", "AUC with windows of eight slots at 5~dB")):
            lines = [f"{lab} & " + " & ".join(f3(get[(snr, W, s, c)]["auc_mean"]) if (snr, W, s, c) in get else "--" for c, _ in conds) + " \\\\"
                     for s, lab in stats]
            write(name, f"""\\begin{{table}}[h]
\\caption{{{cap}}}
\\centering\\footnotesize
\\begin{{tabular}}{{@{{}}l{'c' * len(conds)}@{{}}}}
\\toprule
Statistic & {' & '.join(l for _, l in conds)} \\\\
\\midrule
""" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


def tab_broad():
    """Broadly trained DiscNRX vs the narrowly trained DiscNRX (seed 0) on identical slots."""
    S = read(os.path.join(DATA, "broad_summary.csv"))
    if not S:
        return False
    get = {(r["cond"], float(r["snr_db"])): r for r in S}
    conds = [("S1", "S1 (matched)"), ("DS600", "DS\\,600"), ("DS1000", "DS\\,1000"), ("CDLA", "CDL-A"),
             ("CDLD", "CDL-D"), ("S2", "S2"), ("V90", "90\\,km/h"), ("V150", "150\\,km/h"),
             ("V250", "250\\,km/h"), ("V400", "400\\,km/h")]

    def auc_cell(r, k):
        return "--" if r is None or r.get(k) in (None, "") else f3(r[k])

    lines = []
    for c, lab in conds:
        r5, r10 = get.get((c, 5.0)), get.get((c, 10.0))
        cells = [f3(r5["bler_DiscNRX"]) if r5 else "--", f3(r5["bler_Broad"]) if r5 else "--",
                 f3(r10["bler_DiscNRX"]) if r10 else "--", f3(r10["bler_Broad"]) if r10 else "--",
                 auc_cell(r5, "auc_conf_d"), auc_cell(r5, "auc_conf_b")]
        lines.append(f"{lab} & " + " & ".join(cells) + " \\\\")
    # The matched-channel cost (SNR at BLER 0.1) and the S4 BLER are quoted in the text (macros
    # brSnrTen*, brSfour*), not in this table.
    write("tab_broad.tex", """\\begin{table}[t]
\\caption{Narrowly (CDL-C, 100~ns, 0--30~km/h) Versus Broadly (CDL A--E, 30--1000~ns, 0--120~km/h) Trained
DiscNRX on Identical Slots: BLER and Single-Slot AUC of the Receiver's Own Confidence (One Training Seed Each)}
\\label{tab:broad}
\\centering
\\footnotesize
\\setlength{\\tabcolsep}{3pt}
\\begin{tabular}{@{}lcccccc@{}}
\\toprule
& \\multicolumn{2}{c}{BLER, 5~dB} & \\multicolumn{2}{c}{BLER, 10~dB} & \\multicolumn{2}{c}{AUC, 5~dB} \\\\
\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}
Condition & Narrow & Broad & Narrow & Broad & Narrow & Broad \\\\
\\midrule
""" + "\n".join(lines) + """
\\bottomrule
\\end{tabular}
\\end{table}
""")
    return True


def tab_pending(name, label, caption, what):
    write(name, f"""\\begin{{table}}[t]
\\caption{{{caption}}}
\\label{{{label}}}
\\centering
\\footnotesize
\\pending{{{what}}}
\\end{{table}}
""")


if __name__ == "__main__":
    tab_detection()
    tab_ablation()
    tab_adapt()
    supp_tables()
    if not tab_matched():
        tab_pending("tab_matched.tex", "tab:matched", "Matched Detection Performance", "matched BLER sweep (exp\\_matched.py)")
    if not tab_s4():
        tab_pending("tab_s4.tex", "tab:s4", "Ray-Traced Scene S4", "S4 evaluation (exp\\_s4.py)")
    tab_broad()                      # only when exp_broad.py has run (author decision D2)
    if not tab_complexity():
        tab_pending("tab_complexity.tex", "tab:complexity", "Complexity and Latency", "complexity run with idle GPU (exp\\_complexity.py)")
